quarkus.langchain4j.ai.gemini.api-key=${GEMINI_API_KEY}
# quarkus.langchain4j.ai.gemini.chat-model.model-id=gemini-1.5-flash-latest

# quarkus.langchain4j.timeout=90s
# 1. Limit for the entire HTTP request
quarkus.http.limits.max-body-size=50M

# 2. Limit for the individual multipart form attribute (the PDF file itself)
quarkus.http.limits.max-form-attribute-size=50M
